src/domain/search/landingPageSearch/LandingPageSearchForm.tsx
src/domain/search/landingPageSearch/landingPageSearch.module.scss
src/domain/search/landingPageSearch/landingPageSearchForm.module.scss
src/styles/globals.scss

- Fixed the search box layout
- Fixed css issues with colors in mobile view
- Removed labels

HH-109: Fix searchbox

---

src/domain/search/eventSearch/AdvancedSearch.tsx
src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
src/domain/search/eventSearch/types.ts
src/domain/search/eventSearch/utils.tsx

When performing the free text search, on search button click or Enter, the search term is not cleared. Filter tags are removed.

HH-108: Fix autocomplete search

---

package.json
yarn.lock

Uses new version of hcrc with default 2 rows navigation

HH-105: 2 Rows top navigation

---

package.json
src/common/apollo/utils.ts
src/common/components/hero/Hero.tsx
src/domain/search/landingPage/LandingPage.tsx
src/pages/index.tsx
src/pages/pages/[...slug].tsx
src/pages/search/index.tsx
yarn.lock

Landing page query from hcrc
- page by template query does not work yet

HH-103: Landing page query

---

.github/workflows/load_tests.yml

Typo on load test workflow file prevent run load tests

Fix typo on load test workflow

---

package.json
src/domain/event/eventPageMeta/EventPageMeta.tsx
src/domain/event/eventPageMeta/__tests__/EventPageMeta.test.tsx
src/domain/seo/meta/PageMeta.tsx
src/hooks/useRHHCConfig.tsx
src/pages/_app.tsx
src/setupTests.ts
yarn.lock

Replaced react-helmet with next/head in all the page components.

SEO meta tags fix for articles and pages

---

src/domain/event/EventPageContainer.tsx
src/domain/event/__tests__/EventPageContainer.test.tsx
src/domain/search/landingPage/LandingPage.tsx
src/pages/_app.tsx
src/pages/courses/[eventId]/index.tsx

Fetch event in getStaticProps so that seo tags are available after build

Fix SEO tags for courses (events)

---

src/common/components/hero/Hero.tsx
src/common/components/hero/hero.module.scss
src/domain/search/landingPage/LandingPage.tsx

When hero link is not set n headless cms, hero box is hidden

HH-106: Hero link conditional hide

---

package.json
src/common-events/components/shareLinks/shareLinks.module.scss
src/domain/search/eventSearch/AdvancedSearch.tsx
src/domain/search/eventSearch/search.module.scss
yarn.lock

-Fix back button style, blue outline on hover
-Fix margins:
- Between main title, date and content
- Sidebar header aligned with main header
- Fix koros margins (now they are smaller)
- Fix mobile margins so the page looks consistent in mobile
- Fix default colors of koros
- Fix margin between sidebar and main content (44px total)

HH-132: Articles layout fix

---

package.json
src/common-events/components/infoWithIcon/infoWithIcon.module.scss
src/common-events/components/keyword/keyword.module.scss
src/domain/event/eventContent/EventContent.tsx
src/domain/event/eventContent/eventContent.module.scss
src/domain/event/eventHero/EventHero.tsx
src/domain/event/eventHero/eventHero.module.scss
src/domain/event/eventInfo/eventInfo.module.scss
src/domain/event/eventLocation/EventLocation.tsx
src/domain/event/eventLocation/eventLocation.module.scss
yarn.lock

- Restyled page layout, hero, content, sidebar.

HH-132: Single course page restyling

---

.github/workflows/review.yml
.github/workflows/staging.yml
docker-compose.yml
k6LoadTests.js

- fix for 'docker-compose up'
- is removed the temporary kolga build hack
- load test tuning

Docker compose fix

---

package.json
src/domain/event/eventClosedHero/eventClosedHero.module.scss
src/domain/event/eventPage.module.scss
src/styles/globals.scss
yarn.lock

Fixing general page layout to make footer be always in the bottom
Restyling the Course not found page
Translations will be fixed in separate PR

HH-133: Layout and course not found page

---

src/domain/search/landingPageSearch/landingPageSearch.module.scss
src/domain/search/landingPageSearch/landingPageSearchForm.module.scss

-Fix font size of the search box header to L
-Fix the input fields alignement

HH-128: Search box for landing page

---

src/domain/event/eventContent/eventContent.module.scss
src/domain/event/eventHero/EventHero.tsx
src/domain/event/eventHero/eventHero.module.scss

Fix styling of the single course page hero based on new design

HH-135: Mobile single course style

---

src/domain/event/eventCard/largeEventCard.module.scss

Fix line height of the search card header
Translations are fixed in the separate ticket

HH-131: Fix line height of the search card header

---

src/domain/search/eventSearch/searchResultList/SearchResultsContainer.tsx
src/domain/search/eventSearch/searchResultList/searchResultList.module.scss

HH-141: Fix search scroll fix

---

src/domain/search/eventSearch/searchResultList/searchResultList.module.scss

Search list scroll improvement

HH-141: Removed not needed styles

---

.github/workflows/production.yml

Production workflow file
**[DEV-443](https://helsinkisolutionoffice.atlassian.net/browse/DEV-443):**

Production workflow

---

.github/workflows/production.yml

add missing additional hostname
**[DEV-443](https://helsinkisolutionoffice.atlassian.net/browse/DEV-443):**

Production additional hostname

---

package.json
src/pages/articles/index.tsx
yarn.lock

feat(archive): show only the articles in selected UI language

---

src/pages/index.tsx

HH-168. No logs were given about the issue in the CMS API.

chore: log the Frontpage's NextJS issues

---

package.json
src/common-events/utils/headless-cms/headlessCmsUtils.tsx
src/domain/article/articleDetails/ArticleDetails.tsx
src/domain/event/eventContent/EventContent.tsx
src/domain/event/eventDetails/EventDetails.tsx
src/domain/event/eventDetails/eventDetails.module.scss
src/hooks/useRHHCConfig.tsx
src/pages/articles/index.tsx
src/pages/index.tsx
yarn.lock

- Added data to the front page carousels and grids
- Events have start and end date and tags
- Articles have tags
- Pages - nothing changed

HH-136: Carousel changes

---

package.json
public/locales/en/common.json
public/locales/fi/common.json
public/locales/sv/common.json
src/common-events/utils/headless-cms/headlessCmsUtils.tsx
src/hooks/useRHHCConfig.tsx
yarn.lock

Frontpage layout fixes
Carousels and grids initial amounts fixed, the load more functionality is removed, sow more link added and styled but but functional (waiting for api changes). Styles for the cards and carousels are adjusted

feat: carousel and layout changes

---

graphql.schema.json
src/common-events/components/category/__tests__/__snapshots__/CategoryFilter.test.tsx.snap
src/domain/nextApi/graphql/generated/graphql.tsx
src/domain/search/eventSearch/AdvancedSearch.tsx
src/domain/search/eventSearch/constants.tsx
src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
src/domain/search/eventSearch/query.ts
src/domain/search/eventSearch/utils.tsx
src/tests/mocks/eventListMocks.ts

Replace audience age params with opposite to fix the search query

fix: min max age filter logic

---

package.json
src/common-events/components/category/categoryFilter.module.scss
src/domain/event/eventDetails/EventDetails.tsx
src/domain/event/eventDetails/eventDetails.module.scss
src/domain/footer/footerCategories.module.scss
src/domain/search/landingPageSearch/landingPageSearch.module.scss
src/pages/articles/index.tsx
yarn.lock

-Fixed margins of the carousel title
-Fixed spacing with and without dots
-Dots sizes
-Font sizes and linehights inside cards
-Fixed mobile view prev next buttons
-Fixed mobile view bug with categories
- Fixed outlines of the cards in carousels

fix: styling of landing page carousels

---

.eslintrc.json
package.json
src/common-events/utils/headless-cms/headlessCmsUtils.tsx
src/domain/article/articleDetails/ArticleDetails.tsx
src/domain/event/EventPageContainer.tsx
src/domain/event/EventUtils.ts
src/domain/event/__tests__/EventUtils.test.ts
src/domain/event/constants.ts
src/domain/event/eventCard/EventCard.tsx
src/domain/event/eventCard/LargeEventCard.tsx
src/domain/event/eventDetails/EventDetails.tsx
src/domain/event/eventHero/EventHero.tsx
src/domain/event/eventInfo/eventList/EventList.tsx
src/domain/search/landingPage/LandingPage.tsx
src/hooks/useRHHCConfig.tsx
src/pages/articles/index.tsx
src/utils/__test__/routerUtils.test.js
src/utils/routerUtils.ts
yarn.lock

- Add placeholder (background fallback) image to Cards, Hero and Page
- Customizable placeholser image(s) can be added to RHHC config : (see another pr https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/43)
https://helsinkisolutionoffice.atlassian.net/browse/HH-150
https://helsinkisolutionoffice.atlassian.net/browse/HH-151

HH-150/HH-151: placeholder image

---

src/common-events/components/multiSelectDropdown/multiSelectDropdown.module.scss
src/common-events/components/rangeDropdown/rangeDropdown.module.scss

Fixed bug with mobile icon colors (can be reproduced on real mobile device only)

fix: mobile icon colors

---

src/common-events/components/dateSelector/dateSelector.module.scss
src/common-events/components/multiSelectDropdown/multiSelectDropdown.module.scss
src/common-events/components/rangeDropdown/rangeDropdown.module.scss

Fix arrow colors for the iphone to be black

fix: fix arrow colors and sizes

---

src/common-events/components/navigation/Navigation.tsx
src/common-events/utils/__tests__/getLocalisedString.ts
src/common-events/utils/headless-cms/service.tsx
src/constants.ts
src/domain/event/EventUtils.ts
src/domain/event/__tests__/EventUtils.test.ts
src/domain/event/eventCard/EventCard.tsx
src/domain/event/eventCard/LargeEventCard.tsx
src/domain/event/eventContent/EventContent.tsx
src/domain/event/eventLocation/EventLocation.tsx
src/domain/event/queryUtils.ts
src/domain/search/eventSearch/SearchPage.tsx
src/domain/search/eventSearch/utils.tsx
src/pages/articles/index.tsx
src/tests/mocks/eventListMocks.ts

HH-110. Added events in all languages to the search results. Prioritize the list of fallback languages

Added events in all languages to the search results

---

package.json
src/common/components/spinner/loadingSpinner.module.scss
yarn.lock

Updated the hcrc reference to use multicolor spinner and fixed the vertical position issue

feat: loading spinner position and color

---

package.json
src/common-events/utils/headless-cms/service.tsx
yarn.lock

Fixed the styling and contents of the page and article items

feat: sidebar contents improvements

---

package.json
src/common/components/spinner/loadingSpinner.module.scss
yarn.lock

Fixed spinner animation to be "static" (before that it was moving and circling same time)

feat: spinnter fix search page

---

package.json
public/locales/en/cms.json
public/locales/fi/cms.json
public/locales/sv/cms.json
src/common-events/utils/headless-cms/headlessCmsUtils.tsx
src/hooks/useRHHCConfig.tsx
src/pages/articles/[...slug].tsx
src/pages/articles/index.tsx
yarn.lock

Adds the tags to the cards in archive page

feat: archive page contents

---

package.json
src/domain/article/articleDetails/ArticleDetails.tsx
src/domain/article/articleDetails/articleDetails.module.scss
yarn.lock

-Fixed tags spacing in article card
-Fixed the Clear all (clears also free search text)
-Fixed the date font size in article card

feat: archive page contents fixes

---

src/common-events/utils/headless-cms/headlessCmsUtils.tsx
src/domain/app/AppConfig.ts
src/domain/event/eventContent/eventContent.module.scss
src/domain/event/queryUtils.ts
src/domain/event/similarEvents/SimilarEvents.tsx
src/domain/event/similarEvents/similarEvents.module.scss
src/domain/search/eventSearch/utils.tsx

HH-83. The similar events got a new refinement: The similar events should be searched with the current event's age group and categories. Also the rendering is now done with the components from the HCRC.

Refactored the similar events

---

package.json
src/common-events/utils/headless-cms/service.tsx
src/domain/article/articleDetails/articleDetails.module.scss
src/domain/event/similarEvents/similarEvents.module.scss
yarn.lock

Tags margin fix
Clear tags logic fix (clears also free text)

feat: fix the article archive

---

package.json
public/locales/en/cms.json
public/locales/en/common.json
public/locales/en/event.json
public/locales/en/home.json
public/locales/fi/cms.json
public/locales/fi/common.json
public/locales/fi/home.json
public/locales/sv/cms.json
public/locales/sv/common.json
public/locales/sv/event.json
public/locales/sv/home.json
public/locales/sv/notFound.json
src/domain/search/eventSearch/AdvancedSearch.tsx
src/domain/search/eventSearch/__tests__/Search.test.tsx
src/domain/search/eventSearch/search.module.scss
src/hooks/useRHHCConfig.tsx
yarn.lock

-Fixed headings in Archive page, Search page and Front page

feat: heading fixes to pages

---

package.json
yarn.lock

Fix the front page carusels query url issues. event type is capitalized.

feat: fix the frontpage carousels

---

src/domain/event/eventHero/EventHero.tsx
src/domain/event/eventHero/eventHero.module.scss

Fix the window resize issue by switching hero to mobil mode on XL screen size

feat: fix hero resizing issue

---

package.json
src/domain/search/eventSearch/search.module.scss
yarn.lock

feat: fix the heading styles

---

package.json
src/domain/search/landingPage/LandingPage.tsx
src/domain/search/landingPage/landingPage.module.scss
yarn.lock

Separate carousels in different coloured sections

feat: sections to the frontpage

---

src/domain/search/landingPage/landingPage.module.scss
src/domain/search/landingPageSearch/LandingPageSearch.tsx
src/domain/search/landingPageSearch/landingPageSearch.module.scss

Fixing the layout issues with frontpage and resizing

feat: fix the frontpage layout

---

README.md

docs(routing): implementation of the Apollo links that transforms URLs

---

src/common-events/components/keyword/Keyword.tsx
src/common-events/components/keyword/keyword.module.scss
src/domain/event/eventKeywords/EventKeywords.tsx

- Fixed the bug with showing all tags without count
- Fixed background color to be transparent for the count + styling

feat: fix tags in cards

---

azure-pipelines-build-devtest.yml
azure-pipelines-build-prod.yml

Pipeline YAML files
